FROM c3sr/pytorch-agent:amd64-gpu-pytorch1.8.1-cuda10.1-latest

ENV PKG github.com/c3sr/mlharness
WORKDIR /c3sr/mlharness

RUN git clone --single-branch --depth=1 --recurse-submodules --branch=master https://${PKG}.git .

RUN apt update && apt install -y python3-dev python3-pip libglib2.0-dev python3-opencv

RUN pip3 install --upgrade pip && pip3 install -U setuptools && \
    pip3 install absl-py numpy wheel torchvision===0.9.1 scipy pycocotools tokenization tensorflow transformers===2.4.0 nnunet

# Install LoadGen
RUN cd inference/loadgen && \
    CFLAGS="-std=c++14 -O3" python3 setup.py bdist_wheel && \
    pip3 install --force-reinstall dist/mlperf_loadgen-0.5a0-cp36-cp36m-linux_x86_64.whl && \
    python3 demos/py_demo_single_stream.py

RUN go get github.com/c3sr/go-cupti@cuda10

RUN cd wrapper && go build -tags=pytorch -buildmode=c-shared -o _wrapper.so

WORKDIR /c3sr/mlharness/Python

ENTRYPOINT [ "python3", "main.py" ]
